name: BlazinJump
author: BlazeTheDev
version: 1.0.1
description: A plugin that allows you to launch when you jump twice for PocketMine
main: iiFlamiinBlaze\BlazinJump\BlazinJump
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]